import { UserRoleEnum } from '../enums/user-role.enum';
import { RequestActionTypeEnum } from '../../core/enums/request-action-type.enum';
import { IRequest } from '../../core/interfaces/request.interface';
import { IRequestAction } from '../../core/interfaces/request-action.interface';
import { IRequestApproval } from '../../core/interfaces/request-approval.interface';

export const REQUESTS: IRequest[] = [
  {
    requestId: 1001,
    staffId: 1,
    staffName: 'محمد رئيف الرفاعي',
    managerId: 201,
    managerName: 'أ.د. سلطان علي العتيبي',
    directManagerId: 101,
    directManagerName: 'د. خالد إبراهيم السعيد',
    collegeName: 'كلية الصيدلة',
    approval: 1,
    completed: false,
    nextActionRole: UserRoleEnum.MANAGERS,
    actions: [
      {
        requestActionId: 1,
        requestId: 1001,
        role: UserRoleEnum.DIRECT_MANAGERS,
        type: RequestActionTypeEnum.APPROVE,
        note: null,
        takenAt: new Date('2026-08-20T09:00:00'),
      },
    ],
  },
  {
    requestId: 1002,
    staffId: 2,
    staffName: 'سارة عبدالله الحربي',
    managerId: 202,
    managerName: 'أ.د. منى عبدالعزيز الزهراني',
    directManagerId: 102,
    directManagerName: 'د. نورة محمد الشمري',
    collegeName: 'كلية تقنية المعلومات',
    approval: 2,
    completed: false,
    nextActionRole: UserRoleEnum.DIRECT_MANAGERS,
    actions: [
      {
        requestActionId: 2,
        requestId: 1002,
        role: UserRoleEnum.MANAGERS,
        type: RequestActionTypeEnum.APPROVE,
        note: null,
        takenAt: new Date('2026-08-21T11:30:00'),
      },
      {
        requestActionId: 3,
        requestId: 1002,
        role: UserRoleEnum.DIRECT_MANAGERS,
        type: RequestActionTypeEnum.REJECT,
        note: 'يرجى مراجعة الوثائق',
        takenAt: new Date('2026-08-22T14:00:00'),
      },
    ],
  },
  {
    requestId: 1003,
    staffId: 5,
    staffName: 'عمر سعد القحطاني',
    managerId: 203,
    managerName: 'أ.د. ياسر تركي البلوي',
    directManagerId: 103,
    directManagerName: 'م. عبدالرحمن فهد الدوسري',
    collegeName: 'كلية الهندسة المدنية',
    approval: 3,
    completed: true,
    nextActionRole: null,
    actions: [
      {
        requestActionId: 4,
        requestId: 1003,
        role: UserRoleEnum.DIRECT_MANAGERS,
        type: RequestActionTypeEnum.APPROVE,
        note: null,
        takenAt: new Date('2026-08-23T08:45:00'),
      },
      {
        requestActionId: 5,
        requestId: 1003,
        role: UserRoleEnum.MANAGERS,
        type: RequestActionTypeEnum.APPROVE,
        note: null,
        takenAt: new Date('2026-08-24T10:15:00'),
      },
      {
        requestActionId: 6,
        requestId: 1003,
        role: UserRoleEnum.ADMIN,
        type: RequestActionTypeEnum.APPROVE,
        note: null,
        takenAt: new Date('2026-08-25T13:00:00'),
      },
    ],
  },
];

export const APPROVALS: IRequestApproval[] = [
  {
    requestApprovalId: 1,
    requestId: 1001,
    staffId: 101,
    staffName: 'د. خالد إبراهيم السعيد',
    approved: true,
    note: null,
    createdAt: new Date('2026-08-20T09:00:00'),
  },
  {
    requestApprovalId: 2,
    requestId: 1002,
    staffId: 102,
    staffName: 'د. نورة محمد الشمري',
    approved: true,
    note: null,
    createdAt: new Date('2026-08-21T11:30:00'),
  },
  {
    requestApprovalId: 3,
    requestId: 1002,
    staffId: 202,
    staffName: 'أ.د. منى عبدالعزيز الزهراني',
    approved: false,
    note: 'يرجى مراجعة الوثائق',
    createdAt: new Date('2026-08-22T14:00:00'),
  },
  {
    requestApprovalId: 4,
    requestId: 1003,
    staffId: 103,
    staffName: 'م. عبدالرحمن فهد الدوسري',
    approved: true,
    note: null,
    createdAt: new Date('2026-08-23T08:45:00'),
  },
  {
    requestApprovalId: 5,
    requestId: 1003,
    staffId: 203,
    staffName: 'أ.د. ياسر تركي البلوي',
    approved: true,
    note: null,
    createdAt: new Date('2026-08-24T10:15:00'),
  },
  {
    requestApprovalId: 6,
    requestId: 1003,
    staffId: 201,
    staffName: 'أ.د. سلطان علي العتيبي',
    approved: true,
    note: null,
    createdAt: new Date('2026-08-25T13:00:00'),
  },
];
