import { UserRoleEnum } from '../enums/user-role.enum';
import { UserStatusEnum } from '../enums/user-status.enum';
import { UserTypeEnum } from '../enums/user-type.enum';
import { IStaff } from '../../core/interfaces/staff.interface';

// export interface IMockUser {
//   readonly sub: number;
//   readonly name: string;
//   readonly username: string;
//   readonly type: UserTypeEnum;
//   readonly roles: UserRoleEnum[];
// }

// ─── Staff ───────────────────────────────────────────────────────────────────

export const STAFF: IStaff[] = [
  {
    staffId: 1,
    name: 'محمد رئيف الرفاعي',
    uid: 'ST-2024-001',
    status: UserStatusEnum.ACTIVE,
    hasRequest: true,
    collegeName: 'كلية الصيدلة',
    collegeAlias: 'pharmacy',
    collegeId: 1,
    type: UserTypeEnum.STAFF,
    roles: [UserRoleEnum.PHARMACY_STAFF],
  },
  {
    staffId: 2,
    name: 'سارة عبدالله الحربي',
    uid: 'ST-2024-002',
    status: UserStatusEnum.ACTIVE,
    hasRequest: true,
    collegeName: 'كلية تقنية المعلومات',
    collegeAlias: 'it',
    collegeId: 2,
    type: UserTypeEnum.STAFF,
    roles: [UserRoleEnum.IT_STAFF],
  },
  {
    staffId: 3,
    name: 'أحمد خالد المطيري',
    uid: 'ST-2024-003',
    status: UserStatusEnum.INACTIVE,
    hasRequest: false,
    collegeName: 'كلية الهندسة المعمارية',
    collegeAlias: 'architecture',
    collegeId: 3,
    type: UserTypeEnum.STAFF,
    roles: [UserRoleEnum.ARCHITICTURE_STAFF],
  },
  {
    staffId: 4,
    name: 'فاطمة يوسف العمري',
    uid: 'ST-2024-004',
    status: UserStatusEnum.ACTIVE,
    hasRequest: true,
    collegeName: 'كلية طب الأسنان',
    collegeAlias: 'dentistry',
    collegeId: 4,
    type: UserTypeEnum.STAFF,
    roles: [UserRoleEnum.DENTISTRY_STAFF],
  },
  {
    staffId: 5,
    name: 'عمر سعد القحطاني',
    uid: 'ST-2024-005',
    status: UserStatusEnum.ACTIVE,
    hasRequest: true,
    collegeName: 'كلية الهندسة المدنية',
    collegeAlias: 'civil_engineering',
    collegeId: 5,
    type: UserTypeEnum.STAFF,
    roles: [UserRoleEnum.CIVIL_ENGINEER_STAFF],
  },
  {
    staffId: 6,
    name: 'ريم فهد العصيمي',
    uid: 'ST-2024-006',
    status: UserStatusEnum.ACTIVE,
    hasRequest: true,
    collegeName: 'كلية الصيدلة',
    collegeAlias: 'pharmacy',
    collegeId: 1,
    type: UserTypeEnum.STAFF,
    roles: [UserRoleEnum.PHARMACY_STAFF],
  },
  {
    staffId: 7,
    name: 'ماجد سالم القحطاني',
    uid: 'ST-2024-007',
    status: UserStatusEnum.ACTIVE,
    hasRequest: true,
    collegeName: 'كلية تقنية المعلومات',
    collegeAlias: 'it',
    collegeId: 2,
    type: UserTypeEnum.STAFF,
    roles: [UserRoleEnum.IT_STAFF],
  },
  {
    staffId: 8,
    name: 'هيا عبدالله الشهري',
    uid: 'ST-2024-008',
    status: UserStatusEnum.ACTIVE,
    hasRequest: true,
    collegeName: 'كلية الهندسة المدنية',
    collegeAlias: 'civil_engineering',
    collegeId: 5,
    type: UserTypeEnum.STAFF,
    roles: [UserRoleEnum.CIVIL_ENGINEER_STAFF],
  },
];

// ─── Direct Managers ─────────────────────────────────────────────────────────
// One per department — always the first person to review a staff member's
// request, before it moves on to the fixed managers below.

export const DIRECT_MANAGERS: IStaff[] = [
  {
    staffId: 101,
    uid: 'ST-2024-101',
    status: UserStatusEnum.ACTIVE,
    hasRequest: false,
    collegeName: 'كلية الصيدلة',
    collegeAlias: 'pharmacy',
    collegeId: 1,
    name: 'د. خالد إبراهيم السعيد',
    type: UserTypeEnum.STAFF,
    roles: [UserRoleEnum.DIRECT_MANAGERS],
  },
  {
    staffId: 102,
    uid: 'ST-2024-102',
    status: UserStatusEnum.ACTIVE,
    hasRequest: false,
    collegeName: 'كلية تقنية المعلومات',
    collegeAlias: 'it',
    collegeId: 2,
    name: 'د. نورة محمد الشمري',
    type: UserTypeEnum.STAFF,
    roles: [UserRoleEnum.DIRECT_MANAGERS],
  },
  {
    staffId: 103,
    uid: 'ST-2024-103',
    status: UserStatusEnum.ACTIVE,
    hasRequest: false,
    collegeName: 'كلية الهندسة المعمارية',
    collegeAlias: 'architecture',
    collegeId: 3,
    name: 'م. عبدالرحمن فهد الدوسري',
    type: UserTypeEnum.STAFF,
    roles: [UserRoleEnum.DIRECT_MANAGERS],
  },
  {
    staffId: 104,
    uid: 'ST-2024-104',
    status: UserStatusEnum.ACTIVE,
    hasRequest: false,
    collegeName: 'كلية طب الأسنان',
    collegeAlias: 'dentistry',
    collegeId: 4,
    name: 'د. لمى سعود القرني',
    type: UserTypeEnum.STAFF,
    roles: [UserRoleEnum.DIRECT_MANAGERS],
  },
  {
    staffId: 105,
    uid: 'ST-2024-105',
    status: UserStatusEnum.ACTIVE,
    hasRequest: false,
    collegeName: 'كلية الهندسة المدنية',
    collegeAlias: 'civil_engineering',
    collegeId: 5,
    name: 'م. فيصل ناصر العنزي',
    type: UserTypeEnum.STAFF,
    roles: [UserRoleEnum.DIRECT_MANAGERS],
  },
];

// ─── Managers ─────────────────────────────────────────────────────────────────
// Always the same 6 people, in the same order, for every request — regardless
// of the requesting staff member's department: المكتبة المركزية، الشؤون
// المالية، الرواتب والأجور، تكنولوجيا المعلومات، المستودع، ثم الموارد البشرية.

export const MANAGERS: IStaff[] = [
  {
    staffId: 201,
    uid: 'ST-2024-201',
    status: UserStatusEnum.ACTIVE,
    hasRequest: true,
    collegeName: 'المكتبة المركزية',
    collegeAlias: 'central_library',
    collegeId: 901,
    name: 'أ.د. سلطان علي العتيبي',
    type: UserTypeEnum.STAFF,
    roles: [UserRoleEnum.MANAGERS],
  },
  {
    staffId: 202,
    uid: 'ST-2024-202',
    status: UserStatusEnum.ACTIVE,
    hasRequest: true,
    collegeName: 'مديرية الشؤون المالية',
    collegeAlias: 'financial_affairs',
    collegeId: 902,
    name: 'أ.د. منى عبدالعزيز الزهراني',
    type: UserTypeEnum.STAFF,
    roles: [UserRoleEnum.MANAGERS],
  },
  {
    staffId: 203,
    uid: 'ST-2024-203',
    status: UserStatusEnum.ACTIVE,
    hasRequest: true,
    collegeName: 'الرواتب والأجور',
    collegeAlias: 'payroll',
    collegeId: 903,
    name: 'أ. ياسر تركي البلوي',
    type: UserTypeEnum.STAFF,
    roles: [UserRoleEnum.MANAGERS],
  },
  {
    staffId: 204,
    uid: 'ST-2024-204',
    status: UserStatusEnum.ACTIVE,
    hasRequest: true,
    collegeName: 'مديرية تكنولوجيا المعلومات',
    collegeAlias: 'it_directorate',
    collegeId: 904,
    name: 'م. بندر سعد الغامدي',
    type: UserTypeEnum.STAFF,
    roles: [UserRoleEnum.MANAGERS],
  },
  {
    staffId: 205,
    uid: 'ST-2024-205',
    status: UserStatusEnum.ACTIVE,
    hasRequest: true,
    collegeName: 'المستودع',
    collegeAlias: 'warehouse',
    collegeId: 905,
    name: 'أ. طارق فهد الحربي',
    type: UserTypeEnum.STAFF,
    roles: [UserRoleEnum.MANAGERS],
  },
  {
    staffId: 206,
    uid: 'ST-2024-206',
    status: UserStatusEnum.ACTIVE,
    hasRequest: true,
    collegeName: 'الموارد البشرية',
    collegeAlias: 'human_resources',
    collegeId: 906,
    name: 'أ.د. هند خالد المالكي',
    type: UserTypeEnum.STAFF,
    roles: [UserRoleEnum.MANAGERS, UserRoleEnum.HUMAN_RESOURCES],
  },
];
